---
title: "Homework 6 - Iterating functions on Chicago cold"
author: "Damian Velasco"
date: "4/6/23"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

## Exercises

### Exercise 1


```{r import-convert-temprature, eval = T}
source("convert_temperature.R")
```

### Exercise 2
```{r sanity-check}
convert_temperature(32)
```

### Exercise 3

```{r, import-data}
loop <- read_csv("data/chicago-loop.csv")
oak_park <- read_csv("data/chicago-oak-park.csv")
south_loop <- read_csv("data/chicago-south-loop.csv")
```

```{r glimpse-data}
glimpse(the_loop)
glimpse(oak_park)
glimpse(south_loop)
```
### Exercise 4

```{r, col-types}
loop <- read_csv("data/chicago-loop.csv", col_types = list(col_date()))

oak_park <- read_csv("data/chicago-oak-park.csv", col_types = list(col_date()))

south_loop <- read_csv("data/chicago-south-loop.csv", col_types = list(col_date()))
```

```{r glimpse-data}
glimpse(the_loop)
glimpse(oak_park)
glimpse(south_loop)
```
### Exercise 5

```{r wrangle-and-merge-data, eval = T}
loop <- loop %>% 
  mutate(neighborhood = "loop") %>% 
  relocate(neighborhood)

south_loop <- south_loop %>% 
  mutate(neighborhood = "south_loop") %>% 
  relocate(neighborhood)

oak_park <- oak_park %>% 
  mutate(neighborhood = "oak_park") %>% 
  relocate(neighborhood)

chicago_temperatures <- loop %>% 
  bind_rows(south_loop) %>% 
  bind_rows(oak_park)
```

### Exercise 6
```{r plot}
ggplot(chicago_temperatures, aes(x = date, y = temperature_high, color = neighborhood)) +
geom_point()
```
### Exercise 7

The data does not support that because the loop is the coldest and oak park is the warmest, and what this is saying that south loop and loop should be warmer but that is not true here.

### Exercise 8

```{r create-list, eval = T}
chicago_temperatures_list <- list(chicago_temperatures$temperature_high,
                                  chicago_temperatures$temperature_avg,
                                  chicago_temperatures$temperature_low)
```

### Exercise 9



### Exercise 10

```{r rejoin-data, eval = F}
___ %>% 
    pivot_longer(
    names_to = "measurement",
    values_to = "fahrenheit",
    cols = 3:5
  ) %>% 
  select(___, ___) %>% 
  bind_cols(chicago_temperatures_converted)
```

